### ISSUE TITLE
IronSource Crash on Android

### ISSUE THREAD

**Issue by ventr1x** [distriqt/ANE-Adverts-Mediation#33]
After updating to newest ANE I get the following exception:
Yes, the ANEs are all included, just replaced, even cleared intellij caches.

The only difference to the doc I see is the class name.
Doc mentions `IronSource.init(); ` and I can only find and use `AdMobIronSource.instance.init();`

```
08-24 15:45:36.773 15206 16355 V ironSourceSDK: INTERNAL: IronSourceObject connectAndGetServerResponse - encrypt
08-24 15:45:36.780 15206 16355 E AndroidRuntime: FATAL EXCEPTION: IronSourceInitiatorHandler
08-24 15:45:36.780 15206 16355 E AndroidRuntime: Process: *, PID: 15206
08-24 15:45:36.780 15206 16355 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
08-24 15:45:36.780 15206 16355 E AndroidRuntime: 	at com.ironsource.mediationsdk.utils.ApplicationGeneralSettings.<init>(Unknown Source:2)
08-24 15:45:36.780 15206 16355 E AndroidRuntime: 	at com.ironsource.mediationsdk.utils.ApplicationGeneralSettings.<init>(ApplicationGeneralSettings.kt:5)
08-24 15:45:36.780 15206 16355 E AndroidRuntime: 	at com.ironsource.mediationsdk.utils.ApplicationGeneralSettings.<init>(Unknown Source:3)
08-24 15:45:36.780 15206 16355 E AndroidRuntime: 	at com.ironsource.mediationsdk.utils.ServerResponseWrapper.parseConfigurations(ServerResponseWrapper.java:999)
08-24 15:45:36.780 15206 16355 E AndroidRuntime: 	at com.ironsource.mediationsdk.utils.ServerResponseWrapper.<init>(ServerResponseWrapper.java:202)
08-24 15:45:36.780 15206 16355 E AndroidRuntime: 	at com.ironsource.mediationsdk.IronSourceObject.connectAndGetServerResponse(IronSourceObject.java:2434)
08-24 15:45:36.780 15206 16355 E AndroidRuntime: 	at com.ironsource.mediationsdk.IronSourceObject.getServerResponse(IronSourceObject.java:2333)
08-24 15:45:36.780 15206 16355 E AndroidRuntime: 	at com.ironsource.mediationsdk.MediationInitializer$1.run(MediationInitializer.java:168)
08-24 15:45:36.780 15206 16355 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
08-24 15:45:36.780 15206 16355 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-24 15:45:36.780 15206 16355 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
08-24 15:45:36.780 15206 16355 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
08-24 15:45:36.780 15206 16355 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
08-24 15:45:36.780 15206 16355 E AndroidRuntime: 	... 12 more
```

**Comment by marchbold** [comment]
That is an error in the docs, I'll get it corrected. It should be 

`AdMobIronSource.instance.init();`

That error is because IronSource has added a dependency on `com.jetbrains.kotlin` lib. Add that extension and you should be running again. I'll double check this is in the documentation for the mediator but you can find it in the IronSource docs if you need a link https://docs.airnativeextensions.com/docs/ironsource/add-the-extension#android-support

**Comment by ventr1x** [comment]
Works so far.
Yes, it is not mentioned in the adverts or mediation docs.
