### ISSUE TITLE
The audience_network.dex file installed by apm is different

### ISSUE THREAD

**Issue by ryopei** [distriqt/ANE-Adverts-Mediation#46]
The audience_network.dex file in this repository is 3.25MB, but the one installed using apm is 4.1MB and different files are installed.

And the one installed using apm does not work properly.

##### Environment 

- AIR SDK version: 
- Device OS: Android 12
- Device version: 
- Development IDE: Intellij IDEA Ultimate
- Development OS: Mac OS 12.4

##### Logs
```
07-05 16:21:15.495 30133 30479 E System  : Unable to load dex files
07-05 16:21:15.496 30133 30479 E System  : java.io.IOException: Failed to open dex files from memory: Failure to verify dex file '/data/user/0/xxxxx/Anonymous-DexFile@4021077282.jar': Bad file size (4103310, expected 3183472573)
07-05 16:21:15.496 30133 30479 E System  : 	at dalvik.system.DexFile.openInMemoryDexFilesNative(Native Method)
07-05 16:21:15.496 30133 30479 E System  : 	at dalvik.system.DexFile.openInMemoryDexFiles(DexFile.java:389)
07-05 16:21:15.496 30133 30479 E System  : 	at dalvik.system.DexFile.<init>(DexFile.java:117)
07-05 16:21:15.496 30133 30479 E System  : 	at dalvik.system.DexPathList.initByteBufferDexPath(DexPathList.java:264)
07-05 16:21:15.496 30133 30479 E System  : 	at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:188)
07-05 16:21:15.496 30133 30479 E System  : 	at dalvik.system.InMemoryDexClassLoader.<init>(InMemoryDexClassLoader.java:40)
07-05 16:21:15.496 30133 30479 E System  : 	at dalvik.system.InMemoryDexClassLoader.<init>(InMemoryDexClassLoader.java:52)
07-05 16:21:15.496 30133 30479 E System  : 	at dalvik.system.InMemoryDexClassLoader.<init>(InMemoryDexClassLoader.java:63)
07-05 16:21:15.496 30133 30479 E System  : 	at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.createInMemoryClassLoader(DynamicLoaderFactory.java:341)
07-05 16:21:15.496 30133 30479 E System  : 	at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.makeAdsSdkClassLoader(DynamicLoaderFactory.java:287)
07-05 16:21:15.496 30133 30479 E System  : 	at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.doMakeLoader(DynamicLoaderFactory.java:217)
07-05 16:21:15.496 30133 30479 E System  : 	at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.access$000(DynamicLoaderFactory.java:41)
07-05 16:21:15.496 30133 30479 E System  : 	at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory$1.run(DynamicLoaderFactory.java:101)
```

**Comment by marchbold** [comment]
Apologies, still seem to be having issues with some of our build scripts with assets in these packages.

I'll get this corrected.

**Comment by marchbold** [comment]
Let me know if you still have an issue with the update. Package is deploying now.

**Comment by marchbold** [comment]
Argh... Apologies I'll look into this today...

**Comment by marchbold** [comment]
Okay, they should be available now. Apologies again.

**Comment by marchbold** [comment]
Excellent, thanks for your patience.
