### ISSUE TITLE
New Crash Android 7 and 8

### ISSUE THREAD

**Issue by megajogos** [distriqt/ANE-Adverts-Mediation#52]
We have a lot of new crashes from Adverts on Android 7 and 8.

##### Environment 

- AIR SDK version: 50.0.1.3
- Device OS: Android
- Development OS: Android 8 and 7

##### Logs
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getWidth()' on a null object reference
       at aer.c(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200000.473771314.473771314:5)
       at adf.h(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200000.473771314.473771314:1)
       at com.google.android.gms.ads.internal.i.h(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200000.473771314.473771314:2)
       at com.google.android.gms.ads.nonagon.ad.j.e(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200000.473771314.473771314:1)
       at com.google.android.gms.ads.nonagon.ad.g.run(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200000.473771314.473771314)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

![image](https://user-images.githubusercontent.com/42586185/203171315-2b6fc7a6-9973-4dd2-b2fe-5faa1b72ea80.png)

**Comment by megajogos** [comment]
I recreated this issue on Adverts project: https://github.com/distriqt/ANE-Adverts/issues/440 
I think correct project is Adverts I may close this one.

**Comment by marchbold** [comment]
Yes will follow up with you in the other issue. Cheers
