### ISSUE TITLE
admob mediation Unity app crash

### ISSUE THREAD

**Issue by ronyarbiv** [distriqt/ANE-Adverts-Mediation#66]
If you are reporting a bug please make FATAL EXCEPTION: main
                                                                                                    Process: air.com, PID: 28643
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/webkit/WebViewFeature;
                                                                                                    	at com.unity3d.services.core.webview.WebView.<init>(WebView.kt:83)
                                                                                                    	at com.unity3d.services.core.webview.WebViewApp.<init>(WebViewApp.java:63)
                                                                                                    	at com.unity3d.services.core.webview.WebViewApp.<init>(WebViewApp.java:49)
                                                                                                    	at com.unity3d.services.core.webview.WebViewApp.<init>(WebViewApp.java:33)
                                                                                                    	at com.unity3d.services.core.webview.WebViewApp$1.run(WebViewApp.java:312)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8001)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1039)
                                                                                                    Caused by: java.lang.ClassNotFoundException: androidx.webkit.WebViewFeaturesure you fill out the following information, otherwise delete this template and ask your question.

##### Environment 

- AIR SDK version: 
- Device OS: 
- Device version: 
- Development IDE: 
- Development OS:

##### Logs

Device logs if relevant

**Comment by marchbold** [comment]
Please add the `androidx.webkit` extension, I believe we have missed this from the dependencies list.
