### ISSUE TITLE
Bugs identified in the Pangle lib

### ISSUE THREAD

**Issue by megajogos** [distriqt/ANE-Adverts-Mediation#78]
Hi, I am using Pangle lib version 6.2.0, and analyzing the logs I noticed that whenever a banner is loaded in the test environment the following errors appear:

```
18:06:37.338 PGA                     air.br.com.megajogos.mobile          E  PgaUtilsParamSize: unsuported param GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS, assuming size 1
18:06:37.341 com.distri...namicLinks air.br.com.megajogos.mobile          D  DynamicLinksController::onSuccess()
18:06:37.341 com.distri...pplication air.br.com.megajogos.mobile          D  DisplayController::onSystemUiVisibilityChange( 0 )
18:06:37.341 com.distri...pplication air.br.com.megajogos.mobile          D  DisplayController::updateVisibility(): unknown
18:06:37.341 com.distri...pplication air.br.com.megajogos.mobile          D  DisplayController::ASV::onSystemUiVisibilityChange::OVERRIDE
18:06:37.553 PGA                     air.br.com.megajogos.mobile          E  PgaUtilsParamSize: unsuported param GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS, assuming size 1
18:06:37.607 PGA                     air.br.com.megajogos.mobile          E  PgaUtilsParamSize: unsuported param GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS, assuming size 1
18:06:37.687 FIAM.Headless           air.br.com.megajogos.mobile          I  Successfully fetched 0 messages from backend
18:06:37.711 ignored                 air.br.com.megajogos.mobile          E  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
18:06:38.200 Ads                     air.br.com.megajogos.mobile          I  JS: The jsLoaded GMSG has been sent (https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html:792)
18:06:38.200 chromium                air.br.com.megajogos.mobile          I  [INFO:CONSOLE(792)] "The jsLoaded GMSG has been sent", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html (792)
18:06:38.530 ignored                 air.br.com.megajogos.mobile          E  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
18:06:39.767 InputMetho...gerService system_server                       system_server                        D  packageName=air.br.com.megajogos.mobile, activityName=.AIRAppEntry
18:06:39.942 air.br.com...gos.mobile air.br.com.megajogos.mobile          I  stage height 1280
18:06:39.943 com.distri...pplication air.br.com.megajogos.mobile          D  DisplayController::willCutoutAffectView()
18:06:39.944 com.distri...pplication air.br.com.megajogos.mobile          D  DisplayController::willCutoutAffectView(): 36 > 36
18:06:40.028 GoogleApiManager        air.br.com.megajogos.mobile          E  Failed to get service from broker. 
                                                                                                                 java.lang.SecurityException: Unknown calling package name 'com.google.android.gms'.
                                                                                                                 	at android.os.Parcel.readException(Parcel.java:1692)
                                                                                                                 	at android.os.Parcel.readException(Parcel.java:1645)
                                                                                                                 	at anbn.a(:com.google.android.gms@243834008@24.38.34 (040800-681941525):36)
                                                                                                                 	at amzu.z(:com.google.android.gms@243834008@24.38.34 (040800-681941525):116)
                                                                                                                 	at amhb.run(:com.google.android.gms@243834008@24.38.34 (040800-681941525):54)
                                                                                                                 	at android.os.Handler.handleCallback(Handler.java:751)
                                                                                                                 	at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                                 	at bpiw.lB(:com.google.android.gms@243834008@24.38.34 (040800-681941525):1)
                                                                                                                 	at bpiw.dispatchMessage(:com.google.android.gms@243834008@24.38.34 (040800-681941525):5)
                                                                                                                 	at android.os.Looper.loop(Looper.java:154)
                                                                                                                 	at android.os.HandlerThread.run(HandlerThread.java:61)
18:06:40.396 PGA                     air.br.com.megajogos.mobile          E  PgaUtilsParamSize: unsuported param GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS, assuming size 1
18:06:40.557 cr_MediaCodecUtil       air.br.com.megajogos.mobile          E  Encoder for type video/x-vnd.on2.vp8 is not supported on this device [requireSoftware=false, requireHardware=true].
18:06:40.574 cr_MediaCodecUtil       air.br.com.megajogos.mobile          W  HW encoder for video/avc is not available on this device.
```
```
18:29:08.872 air.br.com...gos.mobile air.br.com.megajogos.mobile          I  [INFO] DistriqtAnalyticsExtension: DistriqtAnalyticsExtension.trackEventObject(), event: 18:29:08.873 air.br.com...gos.mobile air.br.com.megajogos.mobile          I  log: ExtensionManager.getAttributionExtension()
18:29:08.893 ResourceType            air.br.com.megajogos.mobile          W  No known package when getting name for resource number 0x1f000008
18:29:08.917 PGA                     air.br.com.megajogos.mobile          E  PgaUtilsParamSize: unsuported param GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS, assuming size 1
18:29:08.964 chromium                air.br.com.megajogos.mobile          I  [INFO:CONSOLE(2)] "【Bridge】该版本有 Break Change，使用请注意兼容性，详见：https://zjsms.com/JXKorkC/", source: https://sf16-static.i18n-pglstatp.com/obj/ad-pattern-va/renderer/a8784d/index.js (2)
18:29:08.966 chromium                air.br.com.megajogos.mobile          I  [INFO:CONSOLE(2)] "Cannot freeze", source: https://sf16-static.i18n-pglstatp.com/obj/ad-pattern-va/renderer/a8784d/index.js (2)
18:29:09.026 Settings                air.br.com.megajogos.mobile          W  Setting adb_enabled has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
18:29:09.028 BatteryDataWatcher      air.br.com.megajogos.mobile          D  obtainCurrentState: registerReceiver result is Intent { act=android.intent.action.BATTERY_CHANGED flg=0x60000010 (has extras) }
18:29:09.029 ResourceType            air.br.com.megajogos.mobile          W  No known package when getting name for resource number 0x1f000008
18:29:09.035 Settings                air.br.com.megajogos.mobile          W  Setting adb_enabled has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
18:29:09.038 Settings                air.br.com.megajogos.mobile          W  Setting adb_enabled has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
18:29:09.046 MediaPlayer             air.br.com.megajogos.mobile          W  setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
18:29:09.072 Settings                air.br.com.megajogos.mobile          W  Setting adb_enabled has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
18:29:09.087 chromium                air.br.com.megajogos.mobile          E  [ERROR:tile_manager.cc(980)] WARNING: tile memory limits exceeded, some content may not draw
18:29:09.088 chromium                air.br.com.megajogos.mobile          E  [ERROR:tile_manager.cc(980)] WARNING: tile memory limits exceeded, some content may not draw
18:29:09.102 PGA                     air.br.com.megajogos.mobile          I  tid 16131: glGetString GL_VENDOR = Qualcomm
```

**Comment by marchbold** [comment]
Are the banners displaying correctly or is this error causing issues?

**Comment by megajogos** [comment]
The banners appear normally. However, these errors caught my attention. Another thing that happened was that I was unable to generate an iOS app with this new lib, this message appears when I run the command line:

```
0  0x103da0f7a  __assert_rtn + 139
1  0x103dad0c3  ld::tool::SymbolTableAtom<arm64>::encode() (.cold.1) + 35
2  0x103c986c3  ld::tool::SymbolTableAtom<arm64>::encode() + 1475
3  0x103c8347e  ___ZN2ld4tool10OutputFile20buildLINKEDITContentERNS_8InternalE_block_invoke_3 + 30
4  0x7ff80fa947fb  _dispatch_call_block_and_release + 12
5  0x7ff80fa95a44  _dispatch_client_callout + 8
6  0x7ff80faa592a  _dispatch_root_queue_drain + 991
7  0x7ff80faa5e4d  _dispatch_worker_thread2 + 160
8  0x7ff80fc11c9d  _pthread_wqthread + 256
A linker snapshot was created at:
        /tmp/aot1418056061438802904.tmp-2024-10-21-144955.ld-snapshot
ld: Assertion failed: (_machoSection != 0), function machoSection, file ld.hpp, line 1311.

Compilation failed while executing : ld64
```

**Comment by megajogos** [comment]
Any news about the error caused on iOS?

**Comment by marchbold** [comment]
We have an update rolling out shortly which is worth trying however I'd also suggest ensuring you are packaging against a recent version of the iOS SDK, either using the platformsdk command line option or by setting the path to the ios sdk in the air sdk manager.

**Comment by marchbold** [comment]
Latest release is out now, I'd suggest updating and see if you still encounter these issues.
